# When to start alerting staff of ignores on a player (0 to disable)
alert_threshold: 3


# Cross-server messaging config
server_name: null
redis:
  enabled: false
  server: localhost
  password: null
  timeout: 3000
  port: 6379
  max_connections: 4

# General Message of the day
MOTD: ''

# Moderator Message of the day
MBMOTD: ''

# Administrator Message of the day
ABMOTD: ''
